### ISSUE TITLE
Add confirmation box to sensitive actions

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#1]
Add confirmation box for:

- [x]  Saving Postings
- [x] Delete Postings

**Comment by DEV270201** [comment]
Can I work on this issue?

**Comment by rishirishhh** [comment]
assign me this task please

**Comment by rishirishhh** [comment]
@amandesai01 can we connect over discord or some other means of communications ?

**Comment by amandesai01** [comment]
You can find discord link in readme.

**Comment by raiss15** [comment]
Is this issue still open to work? @amandesai01

**Comment by dhruv0206** [comment]
Hi aman, can I take up this issue.

**Comment by gloriasingh08** [comment]
Hi, Can I take up this task?
