### ISSUE TITLE
Test prettier in a Node.js CI environment

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#109]
As we have discussed https://github.com/profilecity/vidur/pull/108#issuecomment-2320198431,  Now i'm planing to test it with integrating node.js CI. It will ensure that if contributor don't follow the code style then CI would be fail and they have to format code. I need your approvence then will raise another issue. Thanks

**Comment by amandesai01** [comment]
Yes, that is required. Can you add that in this PR as well?

**Comment by shivam-sharma7** [comment]
@amandesai01 My thought is that we should follow a rule for creating a good history of commits that can help us to figure out the problem. So we should do one PR for one problem instead multiple.

Here what my thought but rest up to you. Thanks

**Comment by shivam-sharma7** [comment]
I will be implementing this tomorrow or Monday 😉

**Comment by amandesai01** [comment]
@shivam-sharma7 go ahead with CI.
