### ISSUE TITLE
Load all the posting information while seeding-cache

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#113]
File:
src/server/utils/tasks/seed-cache.ts

- Query postings from postings table. See: src/server/api/public/postings.get.ts
- Set item in `general_memoryStorage` with key `postings`.

**Comment by karthik8239** [comment]
can I pick this issue @amandesai01 ?

**Comment by amandesai01** [comment]
go ahead

**Comment by amandesai01** [comment]
Hi @karthik8239 please raise a draft PR with you current work status. Let me know if you are not available and if I need to do it.

**Comment by karthik8239** [comment]
Hello aman
I got sick yesterday and I am not available.Please proceed taking this task @amandesai01
