### ISSUE TITLE
Display Number of Job Positions Next to "Open Positions" Header

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#126]
### Feature Description

Add a counter next to the "Open Positions" header that shows the total number of active job positions. This counter will automatically update as positions are added or removed.

### Acceptance Criteria

- The number of open positions is displayed next to the "Open Positions" header.
- Total positions should be taken from cache (`general_memoryStorage`).
- The counter updates automatically when job positions are added, edited, or removed (`integrate update in endpoint`).
- The display should follow the format: "Open Positions (X)", where X is the number of positions.

**Comment by karthik8239** [comment]
can I pick this @amandesai01 @devshahofficial ?

**Comment by amandesai01** [comment]
@karthik8239, add total positions number to `/api/public/config` endpoint, fetch in `setup-state.ts`, then use it. See how it is used in other places.
