### ISSUE TITLE
Typo: `decrition` instead `description` in Seo frame

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#132]
Need to fix -> https://github.com/profilecity/vidur/blob/63313189db8d0bbc2eecd0279c8feb40c0edbf58/app/components/admin/SeoFrame.vue#L57

![image](https://github.com/user-attachments/assets/ae9e0190-0be7-4703-9bb0-668d5c8aa9d8)

**Comment by amandesai01** [comment]
feel free to raise PR
