### ISSUE TITLE
Extend db schema for JobPosting

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#136]
Extend db schema for JobPosting to also have a
- optional field validTill, which should be date
- `isExpired` boolean

**Comment by RishiDesai17** [comment]
@amandesai01 Can you assign me to this issue?

**Comment by amandesai01** [comment]
go ahead

**Comment by RishiDesai17** [comment]
PR: https://github.com/profilecity/vidur/pull/152

**Comment by RishiDesai17** [comment]
Updated PR: https://github.com/profilecity/vidur/pull/157

**Comment by kmehul** [comment]
Can I work on this as well?
