### ISSUE TITLE
Extend applications table to store tag id

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#140]
Edit table: `posting_applicants`
Add integer field called `status`, default `-1`
Add small int field called `status_type`, default `0`

**Comment by amandesai01** [comment]
go ahead!

**Comment by shivam-sharma7** [comment]
@amandesai01  Since it's been 2 days and no progress so i'm taking this

**Comment by amandesai01** [comment]
@shivam-sharma7 updated specs
