### ISSUE TITLE
Change Date format for Jobs posted

### ISSUE THREAD

**Issue by devshahofficial** [profilecity/vidur#146]
Date format should be updated to show minutes, later hours for the first 24 hours, then days after 24 hours, and months after 30 days.

Career site - 
![Screenshot 2024-09-11 at 12 03 21 PM](https://github.com/user-attachments/assets/a4b9990f-4a06-4441-8c3b-f1c01a123cac)

Admin Dashboard - 
![Screenshot 2024-09-11 at 12 04 07 PM](https://github.com/user-attachments/assets/4628e0a0-eac3-418a-ab45-209a4a5d4016)

**Comment by HemalDesai** [comment]
@devshahofficial i would like to take this up.

**Comment by devshahofficial** [comment]
assigning it to you @HemalDesai
