### ISSUE TITLE
Change the URL in "Powered by Vidur" watermark

### ISSUE THREAD

**Issue by devshahofficial** [profilecity/vidur#148]
Change the URL from "https://vidurjobs.xyz" to "https://profilecity.xyz/vidur"

![Screenshot 2024-09-12 at 11 06 56 AM](https://github.com/user-attachments/assets/1f1e1744-d926-491e-af58-71ef72bcdb68)

**Comment by HemalDesai** [comment]
@devshahofficial i want to fix this.

**Comment by devshahofficial** [comment]
@HemalDesai assigned!

**Comment by amandesai01** [comment]
@HemalDesai use URL from runtimeConfig
