### ISSUE TITLE
Create database seed to initialise with default tags

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#150]
Create seed function to insert into review tags table following values:
1. title: Approved - parent 4
2. title: Shortlisted - parent 3
3. title: Rejected - parent 2
4. title: Deferred - parent 1
5. title: Pending - parent 0

Context:
Seeds are basically functions which run at the start of server, once in lifetime (kind of like database migration), with purpose being bootstrapping / modification in data as per requirements.

**Comment by shivam-sharma7** [comment]
@amandesai01 I am working on it
