### ISSUE TITLE
Expose via API endpoint

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#151]
Update seed cache to load review-tags in `general__memoryStorage`. (`server/utils/tasks/seed-cache.ts`).
Define API endpoint (`server/api/review-tags/index.get.ts`) to read values from cache, authenticate admin request. (see how postings are served)

**Comment by karthik8239** [comment]
Can I pick this @amandesai01 ?
I will make sure to complete this

**Comment by devshahofficial** [comment]
@karthik8239 assigning you this issue!
