### ISSUE TITLE
The last URL from the featured links section is missing.

### ISSUE THREAD

**Issue by devshahofficial** [profilecity/vidur#160]
Added 4 links here.
![Screenshot 2024-09-16 at 9 36 26 AM](https://github.com/user-attachments/assets/277d7ca5-59a1-4c45-8b5e-222f241cf839)

It doesn't render the last one on the career site. 
![Screenshot 2024-09-16 at 9 36 39 AM](https://github.com/user-attachments/assets/76b937bd-2a19-4a28-8885-e5cfc045243d)

**Comment by shivam-sharma7** [comment]
@devshahofficial check this commit 592b1fe9bfeb663d2cccf4f734f3256202ba5223 there is limit

**Comment by amandesai01** [comment]
https://github.com/profilecity/vidur/commit/592b1fe9bfeb663d2cccf4f734f3256202ba5223

As a resolution, I added information to user informing about limit. We still allow to add more links because there are plans in future to create customisable career page.

cc: @devshahofficial @shivam-sharma7
