### ISSUE TITLE
CI/CD pipeline for onboarding Enterprise clients.

### ISSUE THREAD

**Issue by harshil15999** [profilecity/vidur#163]
Problems: Currently we are onboarding clients manually and that would take a lot of time

Solution : We should create a CI/CD pipeline so that we can onboard them in a faster way 
i. Either they should be able to onboard themselves 
ii. We should be able to onboard them quickly.

Follow up features would be to store their assets, company themes etc to provide them with a proper white labelled solution

**Comment by amandesai01** [comment]
This is not required as of now. Onboarding requires several manual steps plus some non-public code involved.
