### ISSUE TITLE
Optimize nuxt application build process

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#179]
The `.nuxtignore` file lets Nuxt ignore files in your project’s root directory during the build phase.

Check docs- https://nuxt.com/docs/guide/directory-structure/nuxtignore

There are files which is not require during build process.

`README.md`
`.gitignore`
`.dockerignore`
`Dockerfile`
`.env`

**Comment by amandesai01** [comment]
Actually that is to ignore specific JS/TS files, which without this, would be included. Current files are excluded anyways, so it is fine.
