### ISSUE TITLE
New casing param in `drizzle-orm` and `drizzle-kit`

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#192]
There are more improvements you can make to your schema definition. The most common way to name your variables in a database and in TypeScript code is usually snake_case in the database and camelCase in the code. For this case, in Drizzle, you can now define a naming strategy in your database to help Drizzle map column keys automatically. 

Let's take a table from the previous example and make it work with the new casing API in Drizzle

```javascript
import { pgTable } from "drizzle-orm/pg-core";

export const ingredients = pgTable("ingredients", (t) => ({
  id: t.uuid().defaultRandom().primaryKey(),
  name: t.text().notNull(),
  description: t.text(),
  inStock: t.boolean().default(true),
}));
```
`inStock` doesn't have a database name alias, but by defining the casing configuration at the connection level, all queries will automatically map it to `snake_case`

Also, we are managing it manually.

**Comment by shivam-sharma7** [comment]
> Also, we are managing it manually.

@amandesai01 Can you confirm?

**Comment by amandesai01** [comment]
Issue is valid. Can you raise a PR?

**Comment by rjsamra** [comment]
We should wait on this.
