### ISSUE TITLE
Markdown Editor - WYSIWYG

### ISSUE THREAD

**Issue by devshahofficial** [profilecity/vidur#22]
Replace the TextArea, with the markdown editor - admin/postings/edit.vue .

**Comment by aaditya9899** [comment]
hey I can work upon this

**Comment by pramaths** [comment]
hey can I work on this @devshahofficial

**Comment by goyalsaksh** [comment]
@amandesai01 please assign this issue to me , I would love to work on it.

**Comment by amandesai01** [comment]
Please add a proposal on how you would approach this.

**Comment by pramaths** [comment]
https://classic.yarnpkg.com/en/package/simplemde

Using this markdown package change the text area to markdown and add some look and feel options like preview etc..

**Comment by Pheewww** [comment]
@amandesai01 can u pls tell how to create admin/posting/edit page as i am directed to linkedin login and then set as user in db. I created  an admin in db but where to put email to get to page, is there supposed to be a other way?

**Comment by pramaths** [comment]
@amandesai01 should I work on this>?

**Comment by amandesai01** [comment]
@Pheewww you can join discord from readme and see setup instructions there. If you face any issue you can discuss there.

**Comment by amandesai01** [comment]
@pramaths give it a try, looks promising. Create a Nuxt Module first in src/modules folder. Refer nuxt documentation.
