### ISSUE TITLE
Create a prod docker image and publish on docker hub.

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#34]
A production docker image which starts vidur server.

**Comment by AdityaPandey03** [comment]
can you assign me this issue?

**Comment by guptaaryan16** [comment]
Can I take this up? @amandesai01

**Comment by amandesai01** [comment]
@AdityaPandey03 sending over to you, @guptaaryan16 you can claim issues in some time.

cc: @akashvarun10 you can help Aditya track this.
Feel free to have further discussions here.

**Comment by AdityaPandey03** [comment]
Sure!

**Comment by amandesai01** [comment]
@AdityaPandey03 please hold on this.

**Comment by akashvarun10** [comment]
@amandesai01 It's best to push to dockerhub via profilecity official account and keeping it as public image we will be also able to access it

**Comment by amandesai01** [comment]
Yes, obviously the pushing part was meant to be done by admins.
