### ISSUE TITLE
Add node.js github action

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#37]
it will allows you to automate build, test, and deployment pipeline.

**Comment by shivam-sharma7** [comment]
@amandesai01 I would love to work on this

**Comment by goyalsaksh** [comment]
@amandesai01 I would like to work on it , please assign this to me.

**Comment by amandesai01** [comment]
Hey @shivam-sharma7, currently we don't have testing / deployment. So closing this, will let you know if needed in future, Thanks.

**Comment by shivam-sharma7** [comment]
@amandesai01 But it will also test and build the project in case anyone push some bug contain code, syntax error and dependecies etc. And you're menually checking right now
