### ISSUE TITLE
Add dependabot to manage dependencies upgrades

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#38]
we create `dependabot.yml` File with basic configuration like Configure Dependabot for like npm,  , update shedule can be weekly, target specific branches main and ignore specific dependency like express.

You can also limit the no of PR it will create,

You can review and merge those PRs, there are more commands as to what next can be done, the feature can be toggled from settings

**Comment by shivam-sharma7** [comment]
@amandesai01 I would love to work on this

**Comment by amandesai01** [comment]
sure, love this. Let me know how will you approach this. Write detailed description in first comment. Don't start working immediatly.

**Comment by Pheewww** [comment]
Hey we create `dependabot.yml File` with basic configuration like `Configure Dependabot` for like npm, docker typescript and redis library, `update shedule` can be weekly, target specific branches `main` and ignore specific dependency like `express`.

You can also limit the no of Pull Req it will create, 
 
 You can review and merge those req, there are more commands as to what next can be done, the feature can be toggled from settings

if no ones working then i want to take it as well.

**Comment by Pheewww** [comment]
> sure, love this. Let me know how will you approach this. Write detailed description in first comment. Don't start working immediatly.

Hey we create `dependabot.yml File` with basic configuration like `Configure Dependabot` for like npm, docker typescript and redis library, `update shedule` can be weekly, target specific branches `main` and ignore specific dependency like `express`.

You can also limit the no of Pull Req it will create, 
 
 You can review and merge those req, there are more commands as to what next can be done, the feature can be toggled from settings

if no ones working then i want to take it as well.

**Comment by sarique2003** [comment]
Hey @amandesai01 can I work on this upgrade?

**Comment by shivam-sharma7** [comment]
@sarique2003  No, I already requested to work on this read first comment https://github.com/profilecity/vidur/issues/38#issuecomment-2267115634

**Comment by sarique2003** [comment]
@shivam-sharma7 , my bad. I won't take this issue up.

**Comment by amandesai01** [comment]
@shivam-sharma7 go ahead! let's do this.
