### ISSUE TITLE
Fix: Broken social link

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#42]
In this current image you can see the `X` profile link redirecting to `https://x.com/thenirvanalabs.com` profile page but we need to replace it with `https://x.com/profilecityhq` which redirect to current `X` profile.

![image](https://github.com/user-attachments/assets/874f4155-0477-4616-af0b-40ecd885ae22)

**Comment by shivam-sharma7** [comment]
@amandesai01 I would like to fix it

**Comment by amandesai01** [comment]
This is not part of this repo. Thanks for bringing it to attention, we will fix this. cc: @devshahofficial
