### ISSUE TITLE
JSON Syntax Error in Seed Function

### ISSUE THREAD

**Issue by HardikSJain** [profilecity/vidur#52]
There is an error in the seed function code related to incorrect JSON syntax. The error message received is:
```
 ERROR  [nitro] [unhandledRejection] Expected property name or '}' in JSON at position 2 (line 1 column 3)
```

Steps to Reproduce:
1. Connect a new database and try running the app.

Cause:
The error is due to incorrect JSON syntax in the following line:
```
value: '{ links: [] }',
```
introduced in #48 

Suggested Fix:
```
value: '{"links": []}',
```

**Comment by gloriasingh08** [comment]
can I take up this issue?

**Comment by ChaitanyaKharche** [comment]
i can take this up too, if its open

**Comment by ameyagidh** [comment]
Try 
value: '{"links": []}', 
instead since  uses single quotes and lacks double quotes around the key. JSON keys must be enclosed in double quotes.
