### ISSUE TITLE
Make sure existing db code works properly with supabase postgres.

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#56]

**Comment by ChaitanyaKharche** [comment]
i can take up the subtask too with @darshannere. if not assigned yet

**Comment by harshil15999** [comment]
> i can take up the subtask too with @darshannere. if not assigned yet

This is a triaging issue where not a lot of code change will be required. You need to verify that the drizzle orm supports supabase as a db.

**Comment by funkycadet** [comment]
> > i can take up the subtask too with @darshannere. if not assigned yet
> 
> This is a triaging issue where not a lot of code change will be required. You need to verify that the drizzle orm supports supabase as a db.

@harshil15999 I noticed nothing has been said so far regarding this. I looked into what you mentioned on your last comment, and yes, Drizzle ORM supports Supabase postgres. I made a connection to the sample database I set up with Supabase and it works with the current implementation. All I had to do was update certain environment variables in the env file and I ran the migration script and it worked.

**Comment by harshil15999** [comment]
@funkycadet can I see the supabase data . Post which we can close this issue

**Comment by amandesai01** [comment]
@funkycadet Yes. I was aware that it supports. Just list down what additional variables you had to pass and let @harshil15999 verify your database, maybe we can create a test free account, share credentials here and delete the account as soon as we close the issue.

**Comment by gloriasingh08** [comment]
Can I take up this issue?

**Comment by harshil15999** [comment]
> Can I take up this issue?

This issue is already in progress by someone else

**Comment by funkycadet** [comment]
> @funkycadet can I see the supabase data . Post which we can close this issue
> 
> Cc- @amandesai01

Oh okay. I didn't submit any data. I was able to run the migrations though. Here's how it looks:
![Screenshot from 2024-08-23 13-35-20](https://github.com/user-attachments/assets/53e14054-e871-420b-8a3f-e63701a79023)

**Comment by amandesai01** [comment]
Can you try to create some job postings / hooks, etc?

**Comment by funkycadet** [comment]
If you could direct me on how to do that, I'd really appreciate it. I'm more of a backend guy, so quite some stuff looks strange to me in the codebase.

**Comment by amandesai01** [comment]
I mean using the UI, create those. This is to ensure that inserts, updates and selects work properly.

**Comment by funkycadet** [comment]
Here's what I see when I visit the default route and the login route:

![Screenshot from 2024-08-24 12-04-34](https://github.com/user-attachments/assets/cd9ea025-1dd5-4628-a363-67c931311627)
![Screenshot from 2024-08-24 12-05-15](https://github.com/user-attachments/assets/30ba6278-a11c-412a-897f-d937f3792328)

**Comment by harshil15999** [comment]
I think you have not been logged in correctly.

**Comment by amandesai01** [comment]
@funkycadet yes that was the issue from my end, fixed it.

**Comment by funkycadet** [comment]
> I think you have not been logged in correctly.
> 
> Did you do this:
> # Requirements: A PostgreSQL instance up-and-running.
> # Clone the repo and cd into the folder.
> 
> npm i -g yarn # install yarn package manager, if you don't have already. yarn # install all the dependencies cp .env.example .env # Create env file and fill the fields. (DO NOT CHANGE PORT) yarn migration:apply # Create database schema. yarn dev # Finally, start the dev server.

yep, that was the first thing I did before anything else

**Comment by funkycadet** [comment]
> @funkycadet yes that was the issue from my end, fixed it.

oh okay. i'll sync changes with my fork and check it out

**Comment by funkycadet** [comment]
@amandesai01  The pages are still blank and login doesn't work

**Comment by amandesai01** [comment]
That's weird. Are you running on port 3001? do you see error or blank page? can you post error log if any?

**Comment by funkycadet** [comment]
yeah, thats the port i'm running on. Here's the error I'm getting in my terminal:
![Screenshot from 2024-08-28 11-02-36](https://github.com/user-attachments/assets/696c0ea9-758c-4c90-9138-ecacfef62150)

**Comment by amandesai01** [comment]
Delete cookies and try again.

**Comment by funkycadet** [comment]
Did that, but no difference still. Same error on my terminal and this is what the webpage shows now:
![Screenshot from 2024-08-28 12-53-05](https://github.com/user-attachments/assets/efdca517-6876-423d-9158-24effb2e0a9d)

**Comment by amandesai01** [comment]
That issue is actually coming from profilecity. Let's ignore that, and conclude that postgres from supabase works well with drizzle. Thanks @funkycadet and @harshil15999 for all the efforts.
