### ISSUE TITLE
Strategically layer to optimize the Docker Build cache.

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#58]
Using cache mount for yarn install, so unchanged packages aren’t downloaded every time

```bash

RUN --mount=type=cache,target=/root/.cache/yarn \
    yarn install
```

**Comment by amandesai01** [comment]
@akashvarun10 can you weigh in here?
cc: @manasgandhi99 @harshil15999

You guys can approve this and then @shivam-sharma7 can implement it.

**Comment by akashvarun10** [comment]
Yes, let's add the cache mount, it optimizes the build time..

**Comment by amandesai01** [comment]
@shivam-sharma7 you can start working. Request review from @akashvarun10 once you finalise your work.
