### ISSUE TITLE
Incorrect form labels

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#62]
Search for form labels, and make sure `<label for=<somid>` should match `<input name=<that same id>`

**Comment by HemalDesai** [comment]
Can i take up this task @amandesai01

**Comment by amandesai01** [comment]
go ahead!

**Comment by dhruv0206** [comment]
Hi Aman, if this is open can I take this issue.

**Comment by dongrep** [comment]
I think this issue has been close @amandesai01. Ref to PR #63
