### ISSUE TITLE
Stop versioning  docker compose file

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#74]
Docker Compose is one of the best inventions, it makes local development easy and friction-free. If you are a long-term Docker Compose fanatic like me, you know we have come a long way. Currently, we are using version 2 of Compose, which is written in Golang. Version 1 of Compose was written in Python and has been deprecated. The last update was on May 10, 2021. Since then, the packages haven't received any security updates and it's not recommended to use it due to security reasons.

For instance, to trigger the binary for Compose v1, we used `docker-compose up` or `docker-compose down`, etc., because previously, we had installed the binary separately. Now, it's `docker compose up` with no dash - between 'docker' and 'compose' because Compose now comes pre-installed with Docker as a subcommand (if you are using Docker for Desktop). This was the most visually different change anyone could notice.

Btw, here is one more tip, we are still using the old convention of naming a compose file - `docker-compose.yaml`, start using `compose.yaml`

@amandesai01

**Comment by amandesai01** [comment]
I still don't get the point. What exactly do you want to change? just rename the compose file?

cc: @akashvarun10

**Comment by akashvarun10** [comment]
Even though docker-compose.yaml still works with the new docker compose command ` docker compose up`, I'll be updating to compose.yaml makes sense to keep things up to date

**Comment by shivam-sharma7** [comment]
> Even though docker-compose.yaml still works with the new docker compose command ` docker compose up`, I'll be updating to compose.yaml makes sense to keep things up to date

@akashvarun10 I agree with you!

**Comment by shivam-sharma7** [comment]
Completed 78005b3
