### ISSUE TITLE
Optimize docker build context

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#90]
The `.dockerignore` file is the tool, that can help us to define the Docker build context that really need. Using this file, we can specify ignore rules and exceptions from these rules for files and folder, that won’t be included in the build context and thus won’t be packed into an archive and uploaded to the Docker server.

Not controlling the build context, can also lead to an unintended exposure of the code, commit history, and secrets (keys and credentials).

If you copy files into you Docker image with ADD . or COPY . command, you may unintentionally include your source files, whole git history (a .git folder), secret files (like .aws, .env, private keys), cache and other files not only into the Docker build context, but also into the final Docker image.

Also, excluding unnecessary large files from the docker build context will lead to lower Docker Image size.

@amandesai01 WDYT?

**Comment by akashvarun10** [comment]
@shivam-sharma7  Can you work on this and request a review from me once the changes are made. @amandesai01 is that okay ?
