### ISSUE TITLE
Configure prettier

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#94]
Prettier is an opinionated code formatter

check docs-https://prettier.io/docs/en/

Also, I have created a branch which you can pull and test -> https://github.com/shivam-sharma7/vidur/tree/code-formatter

@amandesai01 @devshahofficial

**Comment by amandesai01** [comment]
we already have a prettier config in place. See `.prettierrc`.

It would be great if you can enable `.vscode` setting to respect the formatter and not mess up code unnecessarily.

**Comment by shivam-sharma7** [comment]
@amandesai01 Yes, But I did this with npm mean if someone run `npm run dev` then it will automatically format all modified codebase and we can also configure precommit hook- https://prettier.io/docs/en/precommit.html which will validate code format code before making commit.

**Comment by amandesai01** [comment]
Go ahead, add the precommit hook as well!

**Comment by amandesai01** [comment]
@shivam-sharma7 please reopen the PR. your current changes are not respecting the prettier config, which is causing issues.

For example, run prettier, change printWidth and run prettier again. You will see that changes won't take effect.

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 please reopen the PR. your current changes are not respecting the prettier config, which is causing issues.
> 

> For example, run prettier, change printWidth and run prettier again. You will see that changes won't take effect.

@amandesai01 It is working well in my local machine and it would change first time after that it will not touch a single file which will not modify.

Also, change printWidth is according your `.prettierrc` config file, so I would say we have to run this for first time to format codes and commit then if you try to make another commit or change, it will not modify all file it will modify unformat files.

Plese feel free share error logs or screenshort. You can still acces my branch to test it here->

**Comment by shivam-sharma7** [comment]
@amandesai01 Please, give me error logs or screenshort.

**Comment by amandesai01** [comment]
I am not getting any error. It's just that files are not getting formatted as expected. Did you follow the reproduction step?
> Run prettier, change printWidth and run prettier again. You will see that changes won't take effect.

**Comment by shivam-sharma7** [comment]
> It's just that files are not getting formatted as expected. 

@amandesai01 Which kind of file not formatted? like - vue or something but all `.ts` file getting formatted in my machine. I have not attached them with this PR #95 

>Did you follow the reproduction step?

Yes, and it is working for `.ts` file. For vue I'm getting some error this is why I have't include `.vue` in config you can see here- https://github.com/shivam-sharma7/vidur/blob/3449d44aa70505e5afa50e8ca64e8462a106a80f/package.json#L14

**Comment by amandesai01** [comment]
Let's circle back on this next week, I am busy with finalising v1.
