### ISSUE TITLE
Create runtime config for extra options

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#98]
Under `runtimeConfig.public` in `nuxt.config.ts` create following fields:

- `github`
- `discord`
- `twitter`
- `version`

And replace hard coding `src/components/Sidebar.vue`

<img width="239" alt="Screenshot 2024-08-23 at 8 15 00 PM" src="https://github.com/user-attachments/assets/6f4d9a21-c644-48ff-bc51-462624434266">

**Comment by shivam-sharma7** [comment]
> Under `runtimeConfig.public` in `nuxt.config.ts` create following fields:
> 
> * `github`
> * `discord`
> * `twitter`
> * `version`
> 
> And replace hard coding `src/components/Sidebar.vue`

@amandesai01 Path should be `src/components/admin/Sidebar.vue` if I currect?
